bookers2-debug-master/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  # , :controllers => {
  #   :registrations => 'users/registrations'
  # }
  
  root 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users,only: [:show,:index,:edit,:update]
  resources :books
  
  resources :books, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy] 
    resources :book_comments, only: [:create, :destroy]
  end
  #フォロー機能  
post 'follow/:id' => 'relationships#follow', as: 'follow' 
post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 
  resources :users do
    member do
     get :following, :followers
    end
  end
  get '/search' => 'search#search'
end

bookers2-debug-master/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
		
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
	
	
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end

end

bookers2-debug-master/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @booknew = Book.new
    #コメント機能
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @book.user_id = current_user.id
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
    redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:user_id, :title, :body)
  end

end

bookers2-debug-master/app/helpers/books_helper.rb
module BooksHelper
end

bookers2-debug-master/app/views/books/_comment.html.erb
   <div>
      <% @book.book_comments.each do |book_comment| %>
      <p><%= attachment_image_tag(book_comment.user, :profile_image, :fill, 60, 60, fallback: "no-image-icon.jpg") %>
        <%= book_comment.user.name %>
          <% if book_comment.user == current_user %>
              <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete,remote: true,class: "btn btn-sm btn-danger" %>
          <% end %>
      </p>
      <% end %>
      </div>

bookers2-debug-master/app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

bookers2-debug-master/app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td>          <!--いいね機能-->
          <div id="favorites_buttons_<%= book.id %>">
          <%= render partial: 'favorites/favorite', locals: { book: book} %>
          </div>
        <!--いいね機能ココまで--></td>
        <td><%= link_to "コメント数:#{book.book_comments.count} ", book_path(book.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

bookers2-debug-master/app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		  		<div class="text-danger">
            <% if @book.errors.any? %>
            <h3><%= @book.errors.count %>errors prohibited</br>
            this obj from being saved:</h3>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            <% end %>
        </div>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

bookers2-debug-master/app/views/books/index.html.erb
<p><% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

bookers2-debug-master/app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info',user: @book.user  %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @booknew %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td>         
          <!--いいね機能-->
          <div id="favorites_buttons_<%= @book.id %>">
          <%= render partial: 'favorites/favorite', locals: { book: @book} %>
          </div>
          <!--いいね機能ココまで--></td>
          
          <td class="comments-count">コメント件数：<%= @book.book_comments.count %></td>
          <% if @book.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <div class= "container">
        <!--コメント一覧-->
        <div id="comments">
        <%= render 'books/comment', locals: {book: @book} %>
        </div>
        <!----------->
        <!--コメント投稿-->
        <div class="form-group">
            <%= form_with(model:[@book, @book_comment],remote: true, method: :post, value: "") do |f| %>
              <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" ,class:"form-control"%>
              <%= f.submit "送信" %>
            <% end %>
        </div>
        <!----------->
      </div>
    </div>
  </div>
</div>