bookers2-debug-master/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  # , :controllers => {
  #   :registrations => 'users/registrations'
  # }
  
  root 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users,only: [:show,:index,:edit,:update]
  resources :books
  
  resources :books, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy] 
    resources :book_comments, only: [:create, :destroy]
  end
  #フォロー機能  
post 'follow/:id' => 'relationships#follow', as: 'follow' 
post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 
  resources :users do
    member do
     get :following, :followers
    end
  end
  get '/search' => 'search#search'
end

bookers2-debug-master/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

bookers2-debug-master/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
  
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

bookers2-debug-master/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2-debug-master/app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete ,remote: true do%>
      ♥<%= book.favorites.count %> 
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post ,remote: true do%>
      ♡<%= book.favorites.count %> 
    <% end %>
  <% end %>
<% end %>

bookers2-debug-master/app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

bookers2-debug-master/app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");